// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	nonce "github.com/componere/incusos-spire/internal/nonce"
	mock "github.com/stretchr/testify/mock"
)

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// ConsumeOnce provides a mock function with given fields: ctx, id, hash, now
func (_m *MockStore) ConsumeOnce(ctx context.Context, id nonce.NonceID, hash nonce.NonceHash, now time.Time) (nonce.Record, error) {
	ret := _m.Called(ctx, id, hash, now)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeOnce")
	}

	var r0 nonce.Record
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, nonce.NonceID, nonce.NonceHash, time.Time) (nonce.Record, error)); ok {
		return rf(ctx, id, hash, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, nonce.NonceID, nonce.NonceHash, time.Time) nonce.Record); ok {
		r0 = rf(ctx, id, hash, now)
	} else {
		r0 = ret.Get(0).(nonce.Record)
	}

	if rf, ok := ret.Get(1).(func(context.Context, nonce.NonceID, nonce.NonceHash, time.Time) error); ok {
		r1 = rf(ctx, id, hash, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ConsumeOnce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeOnce'
type MockStore_ConsumeOnce_Call struct {
	*mock.Call
}

// ConsumeOnce is a helper method to define mock.On call
//   - ctx context.Context
//   - id nonce.NonceID
//   - hash nonce.NonceHash
//   - now time.Time
func (_e *MockStore_Expecter) ConsumeOnce(ctx interface{}, id interface{}, hash interface{}, now interface{}) *MockStore_ConsumeOnce_Call {
	return &MockStore_ConsumeOnce_Call{Call: _e.mock.On("ConsumeOnce", ctx, id, hash, now)}
}

func (_c *MockStore_ConsumeOnce_Call) Run(run func(ctx context.Context, id nonce.NonceID, hash nonce.NonceHash, now time.Time)) *MockStore_ConsumeOnce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(nonce.NonceID), args[2].(nonce.NonceHash), args[3].(time.Time))
	})
	return _c
}

func (_c *MockStore_ConsumeOnce_Call) Return(_a0 nonce.Record, _a1 error) *MockStore_ConsumeOnce_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ConsumeOnce_Call) RunAndReturn(run func(context.Context, nonce.NonceID, nonce.NonceHash, time.Time) (nonce.Record, error)) *MockStore_ConsumeOnce_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockStore) Delete(ctx context.Context, id nonce.NonceID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, nonce.NonceID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id nonce.NonceID
func (_e *MockStore_Expecter) Delete(ctx interface{}, id interface{}) *MockStore_Delete_Call {
	return &MockStore_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockStore_Delete_Call) Run(run func(ctx context.Context, id nonce.NonceID)) *MockStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(nonce.NonceID))
	})
	return _c
}

func (_c *MockStore_Delete_Call) Return(_a0 error) *MockStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_Delete_Call) RunAndReturn(run func(context.Context, nonce.NonceID) error) *MockStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockStore) Get(ctx context.Context, id nonce.NonceID) (nonce.Record, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 nonce.Record
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, nonce.NonceID) (nonce.Record, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, nonce.NonceID) nonce.Record); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(nonce.Record)
	}

	if rf, ok := ret.Get(1).(func(context.Context, nonce.NonceID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id nonce.NonceID
func (_e *MockStore_Expecter) Get(ctx interface{}, id interface{}) *MockStore_Get_Call {
	return &MockStore_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockStore_Get_Call) Run(run func(ctx context.Context, id nonce.NonceID)) *MockStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(nonce.NonceID))
	})
	return _c
}

func (_c *MockStore_Get_Call) Return(_a0 nonce.Record, _a1 error) *MockStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_Get_Call) RunAndReturn(run func(context.Context, nonce.NonceID) (nonce.Record, error)) *MockStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListExpired provides a mock function with given fields: ctx, now
func (_m *MockStore) ListExpired(ctx context.Context, now time.Time) ([]nonce.Record, error) {
	ret := _m.Called(ctx, now)

	if len(ret) == 0 {
		panic("no return value specified for ListExpired")
	}

	var r0 []nonce.Record
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]nonce.Record, error)); ok {
		return rf(ctx, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []nonce.Record); ok {
		r0 = rf(ctx, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]nonce.Record)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListExpired'
type MockStore_ListExpired_Call struct {
	*mock.Call
}

// ListExpired is a helper method to define mock.On call
//   - ctx context.Context
//   - now time.Time
func (_e *MockStore_Expecter) ListExpired(ctx interface{}, now interface{}) *MockStore_ListExpired_Call {
	return &MockStore_ListExpired_Call{Call: _e.mock.On("ListExpired", ctx, now)}
}

func (_c *MockStore_ListExpired_Call) Run(run func(ctx context.Context, now time.Time)) *MockStore_ListExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockStore_ListExpired_Call) Return(_a0 []nonce.Record, _a1 error) *MockStore_ListExpired_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListExpired_Call) RunAndReturn(run func(context.Context, time.Time) ([]nonce.Record, error)) *MockStore_ListExpired_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: ctx, record
func (_m *MockStore) Put(ctx context.Context, record nonce.Record) error {
	ret := _m.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, nonce.Record) error); ok {
		r0 = rf(ctx, record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockStore_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - record nonce.Record
func (_e *MockStore_Expecter) Put(ctx interface{}, record interface{}) *MockStore_Put_Call {
	return &MockStore_Put_Call{Call: _e.mock.On("Put", ctx, record)}
}

func (_c *MockStore_Put_Call) Run(run func(ctx context.Context, record nonce.Record)) *MockStore_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(nonce.Record))
	})
	return _c
}

func (_c *MockStore_Put_Call) Return(_a0 error) *MockStore_Put_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_Put_Call) RunAndReturn(run func(context.Context, nonce.Record) error) *MockStore_Put_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
