// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	attestor "github.com/componere/incusos-spire/internal/attestor"

	mock "github.com/stretchr/testify/mock"
)

// MockBootstrapWriter is an autogenerated mock type for the BootstrapWriter type
type MockBootstrapWriter struct {
	mock.Mock
}

type MockBootstrapWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBootstrapWriter) EXPECT() *MockBootstrapWriter_Expecter {
	return &MockBootstrapWriter_Expecter{mock: &_m.Mock}
}

// ClearBootstrap provides a mock function with given fields: ctx, project, name
func (_m *MockBootstrapWriter) ClearBootstrap(ctx context.Context, project attestor.ProjectName, name attestor.InstanceName) error {
	ret := _m.Called(ctx, project, name)

	if len(ret) == 0 {
		panic("no return value specified for ClearBootstrap")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, attestor.ProjectName, attestor.InstanceName) error); ok {
		r0 = rf(ctx, project, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBootstrapWriter_ClearBootstrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearBootstrap'
type MockBootstrapWriter_ClearBootstrap_Call struct {
	*mock.Call
}

// ClearBootstrap is a helper method to define mock.On call
//   - ctx context.Context
//   - project attestor.ProjectName
//   - name attestor.InstanceName
func (_e *MockBootstrapWriter_Expecter) ClearBootstrap(ctx interface{}, project interface{}, name interface{}) *MockBootstrapWriter_ClearBootstrap_Call {
	return &MockBootstrapWriter_ClearBootstrap_Call{Call: _e.mock.On("ClearBootstrap", ctx, project, name)}
}

func (_c *MockBootstrapWriter_ClearBootstrap_Call) Run(run func(ctx context.Context, project attestor.ProjectName, name attestor.InstanceName)) *MockBootstrapWriter_ClearBootstrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(attestor.ProjectName), args[2].(attestor.InstanceName))
	})
	return _c
}

func (_c *MockBootstrapWriter_ClearBootstrap_Call) Return(_a0 error) *MockBootstrapWriter_ClearBootstrap_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBootstrapWriter_ClearBootstrap_Call) RunAndReturn(run func(context.Context, attestor.ProjectName, attestor.InstanceName) error) *MockBootstrapWriter_ClearBootstrap_Call {
	_c.Call.Return(run)
	return _c
}

// WriteBootstrap provides a mock function with given fields: ctx, project, name, payload
func (_m *MockBootstrapWriter) WriteBootstrap(ctx context.Context, project attestor.ProjectName, name attestor.InstanceName, payload string) error {
	ret := _m.Called(ctx, project, name, payload)

	if len(ret) == 0 {
		panic("no return value specified for WriteBootstrap")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, attestor.ProjectName, attestor.InstanceName, string) error); ok {
		r0 = rf(ctx, project, name, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBootstrapWriter_WriteBootstrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteBootstrap'
type MockBootstrapWriter_WriteBootstrap_Call struct {
	*mock.Call
}

// WriteBootstrap is a helper method to define mock.On call
//   - ctx context.Context
//   - project attestor.ProjectName
//   - name attestor.InstanceName
//   - payload string
func (_e *MockBootstrapWriter_Expecter) WriteBootstrap(ctx interface{}, project interface{}, name interface{}, payload interface{}) *MockBootstrapWriter_WriteBootstrap_Call {
	return &MockBootstrapWriter_WriteBootstrap_Call{Call: _e.mock.On("WriteBootstrap", ctx, project, name, payload)}
}

func (_c *MockBootstrapWriter_WriteBootstrap_Call) Run(run func(ctx context.Context, project attestor.ProjectName, name attestor.InstanceName, payload string)) *MockBootstrapWriter_WriteBootstrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(attestor.ProjectName), args[2].(attestor.InstanceName), args[3].(string))
	})
	return _c
}

func (_c *MockBootstrapWriter_WriteBootstrap_Call) Return(_a0 error) *MockBootstrapWriter_WriteBootstrap_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBootstrapWriter_WriteBootstrap_Call) RunAndReturn(run func(context.Context, attestor.ProjectName, attestor.InstanceName, string) error) *MockBootstrapWriter_WriteBootstrap_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBootstrapWriter creates a new instance of MockBootstrapWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBootstrapWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBootstrapWriter {
	mock := &MockBootstrapWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
