// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: componere/incus/v1alpha1/reference.proto

package incusv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IncusInstanceReference is the broker-submitted workload reference for Incus
// instance attestation.
//
// The resulting type_url is
// type.googleapis.com/componere.incus.v1alpha1.IncusInstanceReference.
//
// This message carries CLAIMS, never facts — every selector is read back from
// Incus by the plugin. Only instance_uuid selects an instance; the remaining
// fields are equality checks that can only narrow the outcome.
//
// Field numbers 1-4 are permanent and new fields append from 5. No field is
// ever repurposed. v1alpha1 may still break, but only via a new type_url.
type IncusInstanceReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// instance_uuid is the SOLE REQUIRED identity anchor. The plugin checks it
	// against the instance config key volatile.uuid.
	InstanceUuid string `protobuf:"bytes,1,opt,name=instance_uuid,json=instanceUuid,proto3" json:"instance_uuid,omitempty"`
	// project is an OPTIONAL lookup scope. Empty means the plugin's configured
	// project. When set, it is checked against the instance record's top-level
	// project.
	Project string `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	// generation_uuid is an OPTIONAL EXPECTATION. When set, it MUST equal the
	// live instance config key volatile.uuid.generation or attestation fails.
	// This is a rollback discriminator — snapshot restore keeps volatile.uuid
	// and installs a fresh random generation.
	GenerationUuid string `protobuf:"bytes,3,opt,name=generation_uuid,json=generationUuid,proto3" json:"generation_uuid,omitempty"`
	// server is an OPTIONAL EXPECTATION. When set, it is checked against the
	// GET /1.0 endpoint identity (environment.certificate_fingerprint or
	// environment.server_name). It is NEVER used to select an endpoint.
	Server        string `protobuf:"bytes,4,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncusInstanceReference) Reset() {
	*x = IncusInstanceReference{}
	mi := &file_componere_incus_v1alpha1_reference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncusInstanceReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncusInstanceReference) ProtoMessage() {}

func (x *IncusInstanceReference) ProtoReflect() protoreflect.Message {
	mi := &file_componere_incus_v1alpha1_reference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncusInstanceReference.ProtoReflect.Descriptor instead.
func (*IncusInstanceReference) Descriptor() ([]byte, []int) {
	return file_componere_incus_v1alpha1_reference_proto_rawDescGZIP(), []int{0}
}

func (x *IncusInstanceReference) GetInstanceUuid() string {
	if x != nil {
		return x.InstanceUuid
	}
	return ""
}

func (x *IncusInstanceReference) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *IncusInstanceReference) GetGenerationUuid() string {
	if x != nil {
		return x.GenerationUuid
	}
	return ""
}

func (x *IncusInstanceReference) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

var File_componere_incus_v1alpha1_reference_proto protoreflect.FileDescriptor

const file_componere_incus_v1alpha1_reference_proto_rawDesc = "" +
	"\n" +
	"(componere/incus/v1alpha1/reference.proto\x12\x18componere.incus.v1alpha1\"\x98\x01\n" +
	"\x16IncusInstanceReference\x12#\n" +
	"\rinstance_uuid\x18\x01 \x01(\tR\finstanceUuid\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12'\n" +
	"\x0fgeneration_uuid\x18\x03 \x01(\tR\x0egenerationUuid\x12\x16\n" +
	"\x06server\x18\x04 \x01(\tR\x06serverBQZOgithub.com/componere/incusos-spire/proto/componere/incus/v1alpha1;incusv1alpha1b\x06proto3"

var (
	file_componere_incus_v1alpha1_reference_proto_rawDescOnce sync.Once
	file_componere_incus_v1alpha1_reference_proto_rawDescData []byte
)

func file_componere_incus_v1alpha1_reference_proto_rawDescGZIP() []byte {
	file_componere_incus_v1alpha1_reference_proto_rawDescOnce.Do(func() {
		file_componere_incus_v1alpha1_reference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_componere_incus_v1alpha1_reference_proto_rawDesc), len(file_componere_incus_v1alpha1_reference_proto_rawDesc)))
	})
	return file_componere_incus_v1alpha1_reference_proto_rawDescData
}

var file_componere_incus_v1alpha1_reference_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_componere_incus_v1alpha1_reference_proto_goTypes = []any{
	(*IncusInstanceReference)(nil), // 0: componere.incus.v1alpha1.IncusInstanceReference
}
var file_componere_incus_v1alpha1_reference_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_componere_incus_v1alpha1_reference_proto_init() }
func file_componere_incus_v1alpha1_reference_proto_init() {
	if File_componere_incus_v1alpha1_reference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_componere_incus_v1alpha1_reference_proto_rawDesc), len(file_componere_incus_v1alpha1_reference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_componere_incus_v1alpha1_reference_proto_goTypes,
		DependencyIndexes: file_componere_incus_v1alpha1_reference_proto_depIdxs,
		MessageInfos:      file_componere_incus_v1alpha1_reference_proto_msgTypes,
	}.Build()
	File_componere_incus_v1alpha1_reference_proto = out.File
	file_componere_incus_v1alpha1_reference_proto_goTypes = nil
	file_componere_incus_v1alpha1_reference_proto_depIdxs = nil
}
