// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	attestor "github.com/componere/incusos-spire/internal/attestor"

	mock "github.com/stretchr/testify/mock"
)

// MockInstanceReader is an autogenerated mock type for the InstanceReader type
type MockInstanceReader struct {
	mock.Mock
}

type MockInstanceReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInstanceReader) EXPECT() *MockInstanceReader_Expecter {
	return &MockInstanceReader_Expecter{mock: &_m.Mock}
}

// ReadEndpointIdentity provides a mock function with given fields: ctx
func (_m *MockInstanceReader) ReadEndpointIdentity(ctx context.Context) (attestor.EndpointIdentity, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReadEndpointIdentity")
	}

	var r0 attestor.EndpointIdentity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (attestor.EndpointIdentity, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) attestor.EndpointIdentity); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(attestor.EndpointIdentity)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInstanceReader_ReadEndpointIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadEndpointIdentity'
type MockInstanceReader_ReadEndpointIdentity_Call struct {
	*mock.Call
}

// ReadEndpointIdentity is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInstanceReader_Expecter) ReadEndpointIdentity(ctx interface{}) *MockInstanceReader_ReadEndpointIdentity_Call {
	return &MockInstanceReader_ReadEndpointIdentity_Call{Call: _e.mock.On("ReadEndpointIdentity", ctx)}
}

func (_c *MockInstanceReader_ReadEndpointIdentity_Call) Run(run func(ctx context.Context)) *MockInstanceReader_ReadEndpointIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInstanceReader_ReadEndpointIdentity_Call) Return(_a0 attestor.EndpointIdentity, _a1 error) *MockInstanceReader_ReadEndpointIdentity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInstanceReader_ReadEndpointIdentity_Call) RunAndReturn(run func(context.Context) (attestor.EndpointIdentity, error)) *MockInstanceReader_ReadEndpointIdentity_Call {
	_c.Call.Return(run)
	return _c
}

// ReadInstanceByUUID provides a mock function with given fields: ctx, uuid, project
func (_m *MockInstanceReader) ReadInstanceByUUID(ctx context.Context, uuid attestor.InstanceUUID, project attestor.ProjectName) (attestor.InstanceRecord, error) {
	ret := _m.Called(ctx, uuid, project)

	if len(ret) == 0 {
		panic("no return value specified for ReadInstanceByUUID")
	}

	var r0 attestor.InstanceRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, attestor.InstanceUUID, attestor.ProjectName) (attestor.InstanceRecord, error)); ok {
		return rf(ctx, uuid, project)
	}
	if rf, ok := ret.Get(0).(func(context.Context, attestor.InstanceUUID, attestor.ProjectName) attestor.InstanceRecord); ok {
		r0 = rf(ctx, uuid, project)
	} else {
		r0 = ret.Get(0).(attestor.InstanceRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, attestor.InstanceUUID, attestor.ProjectName) error); ok {
		r1 = rf(ctx, uuid, project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInstanceReader_ReadInstanceByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadInstanceByUUID'
type MockInstanceReader_ReadInstanceByUUID_Call struct {
	*mock.Call
}

// ReadInstanceByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid attestor.InstanceUUID
//   - project attestor.ProjectName
func (_e *MockInstanceReader_Expecter) ReadInstanceByUUID(ctx interface{}, uuid interface{}, project interface{}) *MockInstanceReader_ReadInstanceByUUID_Call {
	return &MockInstanceReader_ReadInstanceByUUID_Call{Call: _e.mock.On("ReadInstanceByUUID", ctx, uuid, project)}
}

func (_c *MockInstanceReader_ReadInstanceByUUID_Call) Run(run func(ctx context.Context, uuid attestor.InstanceUUID, project attestor.ProjectName)) *MockInstanceReader_ReadInstanceByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(attestor.InstanceUUID), args[2].(attestor.ProjectName))
	})
	return _c
}

func (_c *MockInstanceReader_ReadInstanceByUUID_Call) Return(_a0 attestor.InstanceRecord, _a1 error) *MockInstanceReader_ReadInstanceByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInstanceReader_ReadInstanceByUUID_Call) RunAndReturn(run func(context.Context, attestor.InstanceUUID, attestor.ProjectName) (attestor.InstanceRecord, error)) *MockInstanceReader_ReadInstanceByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInstanceReader creates a new instance of MockInstanceReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInstanceReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInstanceReader {
	mock := &MockInstanceReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
